language: c
compiler:
   - gcc

before_install:
 - lsb_release -a
 - sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots # libsdl2
 - sudo apt-get update -qq

install:
 - sudo apt-get install libsdl2-dev

script:
  - make

notifications:
  email: false

  irc:
    channels:
      - "irc.blitzed.org#3dmoo"
    on_success: always
    on_failure: always
